# Generated by Django 4.2.7 on 2024-05-05 17:23

import apply.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(upload_to='apply/media/uploads/', validators=[apply.models.validate_file_extension]),
        ),
    ]
