# Generated by Django 4.2.7 on 2024-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_useraccount_profile_picture_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
