# Generated by Django 4.2.7 on 2024-03-18 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('starting_date', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('experience', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('applicants', models.IntegerField(default=0)),
                ('job_about', models.TextField()),
                ('other_req', models.TextField()),
                ('vacancy', models.IntegerField()),
                ('catagory', models.ManyToManyField(to='category.category')),
                ('skills', models.ManyToManyField(to='job.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_type', models.ManyToManyField(to='category.jobtype')),
            ],
        ),
    ]
